### ISSUE TITLE
〔建議〕Tabbie 的 icon 不夠明顯

### ISSUE THREAD

**Issue by Apple-Huang** [angusjune/tabbie#2]
一直在尋找合適的這類 Undo closed tabs 套件
目前發現就您的 Tabbie 使用起來邏輯最好
尤其是已關閉分頁的圖標唯有當下視窗裡的是顯示彩色圖標，以及分頁關閉時間在滑鼠懸浮才顯示
大幅增加套件的美觀程度。

不過使用下來有一個地方想跟您提出建議，就是 Tabbie 的 icon 顏色淡到快看不到了（這邊另外安裝 [恢復關閉分頁](https://chrome.google.com/webstore/detail/recover-closed-tab/fcjlmbbejgnfpcgiigpgfacipckopdkf/related) 這個套件做比較），Tabbie 在剛開啟瀏覽器時 icon 是幾乎看不到的，要滑鼠主動點擊後才會變較明顯的白色 icon。不知道有沒有機會改善，謝謝。

https://user-images.githubusercontent.com/43962513/202119507-bf48b150-b7d0-436e-b680-a2893c36fb38.mp4

**Comment by angusjune** [comment]
感谢你的建议
你浏览器/计算机当前的是否设置为「深色模式」？
因为 Chrome 限制的原因，暂时无法在浏览器启动的时候，立即捕获到浏览器的深色模式设置，所以在点击 icon 前，会是默认的深色。若浏览器长期处于深色模式，可以在 Tabbie 的设置中，将深色模式始终开启，此时 icon 会是默认浅色

**Comment by Apple-Huang** [comment]
作者您好，確實我的 Edge 是深色模式。
剛測試了 Edge 在深色模式下，無論將 Tabbie 設置為 Dark 或 Light 兩者 icon 都無變化（都是像一樓提到的情況）。
不知道是不是因為我的瀏覽器是 Edge，而不是 Chrome，造成這樣的差異。

**Comment by angusjune** [comment]
感谢反馈 我会在 edge 上作进一步的调试

**Comment by angusjune** [comment]
> 作者您好，確實我的 Edge 是深色模式。 剛測試了 Edge 在深色模式下，無論將 Tabbie 設置為 Dark 或 Light 兩者 icon 都無變化（都是像一樓提到的情況）。 不知道是不是因為我的瀏覽器是 Edge，而不是 Chrome，造成這樣的差異。

设置为 Dark 后，弹出窗的颜色是否会变为深色模式？

**Comment by Apple-Huang** [comment]
有的，設置 Dark 時彈窗有變深色背景（Light 也有變白色）

![2022-11-18_190046](https://user-images.githubusercontent.com/43962513/202691030-bd7e9c0a-2a7c-4525-8f4b-9c164def2886.png)
![2022-11-18_190035](https://user-images.githubusercontent.com/43962513/202691053-9eef278a-b133-4fdf-ba87-c2db12922395.png)

**Comment by angusjune** [comment]
已经发布了新的 [beta release](https://github.com/angusjune/tabbie/releases/tag/v2.0.0-beta)，稍后会更新至应用商店中。在此之前，你可先行试用，看看是否还有问题存在。

**Comment by Apple-Huang** [comment]
> 已经发布了新的 [beta release](https://github.com/angusjune/tabbie/releases/tag/v2.0.0-beta)，稍后会更新至应用商店中。在此之前，你可先行试用，看看是否还有问题存在。

作者您好，目前試用都OK了，非常感謝您。
P.S. 外觀自訂性又更豐富了👍
